name: Publish
on:
  push:
    tags:
      - '*'

jobs:
  publish:
    name: Tagged build and publish
    runs-on: macos-latest

    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Extract Git Tag
        id: get_tag
        run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Build with Tag Version
        run: ./gradlew assemble --stacktrace -Pversion=$TAG_NAME -PmavenUsername=${{ secrets.CURRENT_GITHUB_USER }} -PmavenPassword=${{ secrets.GITHUB_TOKEN }}

      - name: Publish Vary Library
        run: ./gradlew vary:publish -Pversion=$TAG_NAME -PmavenUsername=${{ secrets.CURRENT_GITHUB_USER }} -PmavenPassword=${{ secrets.GITHUB_TOKEN }}
